sylius_grid:
    grids:
        asdoria_admin_retailer_group:
            driver:
                name: doctrine/orm
                options:
                    class: "%asdoria.model.retailer_group.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: name
                rating:
                    type: twig
                    label: sylius.ui.rating
                    sortable: rating
                    options:
                        template: "@SyliusAdmin/Grid/Field/rating.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    manage:
                        type: links
                        label: asdopria.ui.manage_retailers
                        icon: cubes
                        options:
                            link:
                                route: asdoria_admin_retailer_group_retailers_index
                                parameters:
                                    retailerGroupId: resource.id
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [name]
