services:
    Asdoria\SyliusRetailerPlugin\Menu\AdminMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: !php/const Sylius\Bundle\AdminBundle\Menu\MainMenuBuilder::EVENT_NAME, method: addMenuItems }
