#Asdoria\SyliusRetailerPlugin\Entity\RetailerGroupImage:
#    properties:
#        file:
#            - NotBlank:
#                  groups: [sylius]
#                  message: 'asdoria.ui.retailer_group_image.path.not_blank'
