asdoria_shop_ajax_retailer_index:
    path: /{postCode}
    methods: [GET]
    defaults:
        _controller: asdoria.controller.retailer::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete, Detailed]
            permission: true
            repository:
                method: findBy
                arguments: [postcode: $postCode]
