asdoria_admin_retailer_group:
    resource: |
        alias: asdoria.retailer_group
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: index
        grid: asdoria_admin_retailer_group
        permission: true
        vars:
           all:
             templates:
                form: '@AsdoriaSyliusRetailerPlugin/Admin/RetailerGroup/_form.html.twig'
    type: sylius.resource
