asdoria_admin_retailer_group_retailers_index:
    path: /{retailerGroupId}/retailers
    methods: [GET]
    defaults:
        _controller: asdoria.controller.retailer:indexAction
        _sylius:
            grid: asdoria_admin_retailer_group_retailers
            vars:
                retailerGroup: expr:notFoundOnNull(service('asdoria.repository.retailer_group').find($retailerGroupId))
                templates:
                    breadcrumb: "@AsdoriaSyliusRetailerPlugin/Admin/RetailerGroup/Retailers/Crud/Index/_breadcrumb.html.twig"
                route:
                    parameters:
                        retailerGroupId: $retailerGroupId
            section: admin
            template: '@SyliusAdmin/Crud/index.html.twig'

asdoria_admin_retailer_group_retailers_create:
    path: /{retailerGroupId}/retailers/new
    methods: [GET, POST]
    defaults:
        _controller: asdoria.controller.retailer:createAction
        _sylius:
            redirect:
                route: asdoria_admin_retailer_group_retailers_index
                parameters:
                    retailerGroupId: $retailerGroupId
            section: admin
            template: '@AsdoriaSyliusRetailerPlugin/Admin/RetailerGroup/Retailers/Crud/create.html.twig'
            factory:
                method: createForRetailerGroup
                arguments:
                    - expr:notFoundOnNull(service('asdoria.repository.retailer_group').find($retailerGroupId))
            form:
                type: Asdoria\SyliusRetailerPlugin\Form\Type\RetailerType
                options:
                    validation_groups:
                        - sylius
            vars:
                templates:
                    form: '@AsdoriaSyliusRetailerPlugin/Admin/Retailer/_form.html.twig'
                    breadcrumb: "@AsdoriaSyliusRetailerPlugin/Admin/RetailerGroup/Retailers/Crud/Create/_breadcrumb.html.twig"
                route:
                    name: asdoria_admin_retailer_group_retailers_create
                    parameters:
                        retailerGroupId: $retailerGroupId


asdoria_admin_retailer_group_retailers_update:
    path: /{retailerGroupId}/retailers/{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: asdoria.controller.retailer:updateAction
        _sylius:
            redirect:
                route: asdoria_admin_retailer_group_retailers_index
                parameters:
                    retailerGroupId: $retailerGroupId
            section: admin
            template: '@AsdoriaSyliusRetailerPlugin/Admin/RetailerGroup/Retailers/Crud/update.html.twig'
            form:
                type: Asdoria\SyliusRetailerPlugin\Form\Type\RetailerType
                options:
                    validation_groups:
                        - sylius
            vars:
                route:
                    name: asdoria_admin_retailer_group_retailers_update
                    parameters:
                        retailerGroupId: $retailerGroupId
                        id: $id
                templates:
                    form: '@AsdoriaSyliusRetailerPlugin/Admin/Retailer/_form.html.twig'
                    breadcrumb: "@AsdoriaSyliusRetailerPlugin/Admin/RetailerGroup/Retailers/Crud/Update/_breadcrumb.html.twig"

asdoria_admin_retailer_group_retailers_delete:
    path: /{retailerGroupId}/retailers/{id}
    methods: [DELETE]
    defaults:
        _controller: asdoria.controller.retailer:deleteAction
        _sylius:
            redirect:
                route: asdoria_admin_retailer_group_retailers_index
                parameters: {retailerGroupId: $retailerGroupId}
            section: admin
            vars:
                route:
                    parameters:
                        retailerGroupId: $retailerGroupId
